comment:
  layout: "header, diff, flags, components"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto
        informational: true
    patch:
      default:
        informational: true
