name: Cache stack related directories from haskell-actions/setup

inputs:
  cache-key:
    description: Key for stack related cache
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get stack root directory
      id: stack-root
      shell: bash
      run: |
        echo os: ${{ runner.os }}
        echo runner.tool_cache: ${{ runner.tool_cache }}
        echo RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}

        case ${{ runner.os }} in
          "Windows")
            echo "root=C:sr" >> $GITHUB_OUTPUT
            echo "tool=${RUNNER_TOOL_CACHE}\stack" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "root=${HOME}/.stack" >> $GITHUB_OUTPUT
            echo "tool=${RUNNER_TOOL_CACHE}/stack" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: Cache stack compiler
      uses: actions/cache@v4
      with:
        path: ${{ steps.stack-root.outputs.tool }}
        key: stack-ghc-${{ inputs.cache-key }}

    - name: Cache extra stack related files for windows
      if: runner.os == 'Windows'
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\Programs\stack
        key: stack-windows-extra-${{ inputs.cache-key }}

    - name: Cache files under stack root
      uses: actions/cache@v4
      with:
        path: ${{ steps.stack-root.outputs.root }}
        key: stack-root-${{ inputs.cache-key }}
