name: main

on:
  - push

defaults:
  run:
    shell: bash

jobs:
  hello_world_job:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Write the output time to file
        run: |
          mkdir times
          echo "${{ steps.hello.outputs.time }}" > times/${{ matrix.os }}.txt

      - name: Upload the file containing time output
        uses: actions/upload-artifact@v2
        with:
          name: time-output
          path: times/${{ matrix.os }}.txt

  via_github:
    runs-on: ubuntu-latest
    name: Using root action by repository name
    steps:
      - name: Hello world action
        uses: 8c6794b6/playing-with-github-actions@v1
        id: hello
        with:
          who-to-greet: 'Foo Bar Buzz'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  composite01:
    runs-on: ubuntu-latest
    name: Running composite run steps action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action
        uses: ./.github/actions/composite01
        id: hello
        with:
          who-to-greet: 'Quux'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  ts01:
    runs-on: ubuntu-latest
    name: Running action made with TypeScript
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action
        uses: ./.github/actions/ts01
        id: hello
        with:
          who-to-greet: 'Blah'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Build all
        run: cd .github/actions/ts01 && yarn && yarn clean && yarn all

  release:
    runs-on: ubuntu-latest
    name: Release on new tag
    needs:
      - hello_world_job
      - via_github
      - composite01
      - ts01
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: time-output
          path: times

      - name: Show downloaded artifacts
        run: ls -lh times

      - name: Make release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        id: rel
        with:
          draft: true
          prerelease: true
          body_path: changelogs/latest.txt
          files: |
            times/macos-latest.txt
            times/ubuntu-latest.txt
            times/windows-latest.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show released url
        if: startsWith(github.ref, 'refs/tags')
        run: echo ${{ steps.rel.outputs.url }}
