on:
  - push

jobs:
  hello_world_job:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  via_github:
    runs-on: ubuntu-latest
    name: Using root action by repository name
    steps:
      - name: Hello world action
        uses: 8c6794b6/playing-with-github-actions@v1
        id: hello
        with:
          who-to-greet: 'Foo Bar Buzz'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  composite01:
    runs-on: ubuntu-latest
    name: Running composite run steps action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world actoin
        uses: ./.github/actions/composite01
        id: hello
        with:
          who-to-greet: 'Quux'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
