name: "Pull request"

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  cabal-install:
    runs-on: ubuntu-latest
    uses: ./.github/workflow/hs-hello.yml@${{ github.ref_name }}
    with:
      foo: buzz
      
  #   name: Build hs-hello with cabal-install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Haskell with haskell-actions/setup
  #       uses: haskell-actions/setup@v2
  #       with:
  #         ghc-version: '9.8'
  #         cabal-version: '3.10'

  #     - name: Build and test hs-hello
  #       run: |
  #         cabal update
  #         cabal configure --enable-coverage
  #         cabal build hs-hello
  #         cabal test hs-hello

  #     - name: Generate coverage report
  #       uses: 8c6794b6/hpc-codecov-action@v2
  #       with:
  #         target: cabal:test-main

  #     - name: Upload coverage report
  #       uses: codecov/codecov-action@v3
  #       env:
  #         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
