name: Push and pull

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
    tags:
      - '!**'

  pull_request:

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      dont_skip: |
        ${{ steps.skip_check.outputs.should_skip }} != 'true' ||
        github.ref_name == 'main'
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
      - name: Show some values in github context
        run: |
          echo github.base_ref: ${{ github.base_ref }}
          echo github.ref_name: ${{ github.ref_name }}

  stack:
    needs: pre_job
    if: needs.pre_job.outputs.dont_skip
    uses: ./.github/workflows/hs-hello-stack.yml
    with:
      foo: bar bar bar


    
