name: Push and pull

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
    tags:
      - '!**'

  pull_request:

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      # skip_check: ${{ steps.skip_check.outputs.should_skip }}
      dont_skip: |
        ${{
        steps.skip_check.outputs.should_skip != 'true' ||
        github.ref_name == 'main'
        }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
      - name: Show some values in github context
        run: |
          echo github.base_ref: ${{ github.base_ref }}
          echo github.ref_name: ${{ github.ref_name }}

  show_output:
    runs-on: ubuntu-latest
    needs: pre_job
    steps:
      - name: Show outputs of pre_job
        run: |
          echo dont_skip: ${{ needs.pre_job.outputs.dont_skip }}

  stack:
    needs: pre_job
    # if: |
    #   needs.pre_job.outputs.skip_check != 'true' ||
    #   github.ref_name == 'main'
    if: needs.pre_job.outputs.dont_skip == 'true'
    uses: ./.github/workflows/hs-hello-stack.yml
    with:
      foo: bar bar bar
