name: Push and pull

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
    tags:
      - '!**'

  pull_request:

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5

  stack:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    uses: ./.github/workflows/hs-hello-stack.yml
    with:
      foo: bar bar bar


    
