name: release

# on:
#   push:
#     tags:
#       - 'v*'

on:
  push:
    branches:
      - 'release/*'
  # workflow_run:
  #   workflows: ["main"]
  #   types:
  #     - completed
  #     - requested

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.ref
        run: echo ${{ github.ref }}

      - name: Checkout on new tag
        if: startsWith(github.ref, 'refs/tags')
        uses: actions/checkout@v4

      - name: Build
        run: echo ${{ github.ref }} > Release.txt

      - name: Show workflow
        run: echo ${{ github.workflow }}

      - name: Test
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        id: rel
        with:
          draft: true
          prerelease: true
          body_path: changelogs/latest.txt
          files: |
            Release.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show released url
        run: echo ${{ steps.rel.outputs.url }}
