name: release

# on:
#   push:
#     tags:
#       - 'v*'

on:
  branch:
    - 'release/*'
  # workflow_run:
  #   workflows: ["main"]
  #   types:
  #     - completed
  #     - requested

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.ref
        run: echo ${{ github.ref }}

      - name: Run release steps
        if: startsWith(github.ref, 'refs/tags')
        uses: ./.github/actions/release

      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Build
      #   run: echo ${{ github.ref }} > Release.txt

      # - name: Show workflow
      #   run: echo ${{ github.workflow }}

      # - name: Test
      #   run: cat Release.txt

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   id: rel
      #   with:
      #     draft: true
      #     prerelease: true
      #     body_path: changelogs/latest.txt
      #     files: |
      #       Release.txt
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Show released url
      #   run: echo ${{ steps.rel.outputs.url }}
